// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/partitio/atlas-gentool/testdata/test.proto

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	github.com/partitio/atlas-gentool/testdata/test.proto

It has these top-level messages:
	Example
*/
package test

import strings "strings"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/lyft/protoc-gen-validate/validate"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "github.com/partitio/protoc-gen-gorm/options"
import _ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
import _ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
import _ "github.com/infobloxopen/protoc-gen-preprocess/options"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (m *Example) Preprocess() error {

	m.EmailAddress = strings.ToLower(m.EmailAddress)

	return nil
}
